name: Check Format

on:
  push:
  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Gradle and Java"
        uses: autodata-dev/actions/setup-gradle-and-java@v1
        
      - name: "Check formatting"
        run: ./gradlew spotlessCheck