name: Check Format

on:
  pull_request:
    branches: [ "**" ]

  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Java and Gradle"
        uses: ./github/actions/setup-gradle-and-java@v1
        
      - name: "Check formatting"
        run: ./gradlew spotlessCheck
