name: Check Format

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v3
        
      - name: "Check formatting"
        run: ./gradlew spotlessCheck
