name: Check Format

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Java and Gradle"
        uses: autodata-dev/setup-java-and-gradle/action.yml@v1
        
      - name: "Check formatting"
        run: ./gradlew spotlessCheck
