name: Setup Java & Gradle

on: 
  workflow_call:
    inputs: 
      java-version:
        type: number
        default: 21
        description: The Java JDK version.
      java-distribution:
        type: string
        default: zulu
        description: The JDK distributor to use e.g. OpenJDK, Azul.
      run-build:
        type: boolean
        default: false
        description: A flag to determine if the gradle build command should be run.

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: $inputs.java-distribution
        java-version: inputs.java-version
  
    - name: "Setup Gradle"
      uses: gradle/gradle-build-action@v3

    - if: inputs.run-build
    - name: "Build Gradle"
      run: ./gradlew build 
